# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-28 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_vacation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Album')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AlterModelTable(
            name='vacation',
            table='vacations',
        ),
        migrations.AddField(
            model_name='album',
            name='vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacation'),
        ),
    ]
