# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-28 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_auto_20180727_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacation'),
        ),
    ]
